### PR TITLE
Windows: Add optional file association for ufp-files.

### PR DESCRIPTION
**Pull request by ckielstra**
In the Windows installer, add the option when clicking a ufp-file to open this with Cura.

### CODE REVIEW

**Comment by nallath** [comment]
We don't actually have a UFP reader yet, so we can't merge this just yet.

**Comment by Ghostkeeper** [comment]
Might as well add it for g-code too, then.

**Comment by Ghostkeeper** [comment]
The file association should also be updated in the Linux build (the MIME type stuff).

**Comment by ckielstra** [comment]
This is all feature creep. If UFP-files are not supported yet then I suggest to close this pull request.

**Pull request closed without merging**
