### PR TITLE
CURA-2713: NSIS: Updating commands for Arduino drivers (new)

### PR DESCRIPTION
**Pull request by thopiekar**
Depends on: https://github.com/Ultimaker/cura-binary-data/pull/5

Contributes to CURA-2713

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see CURA-4226 instead. Cura-2713 was closed for being too old, but 4226 is the new one.

**Comment by LipuFei** [comment]
@thopiekar I have changed the paths, but actual they still don't exist. The only EXE installation files are `dpinst-amd64.exe` and `dpinst-x86.exe` in the `arduino` folder. I think we still need to remove those two paths.

**Comment by thopiekar** [comment]
@LipuFei You are right 😮 
Have you every tried to copy the executables from arduino into FTDI? 😅 
Can imagine that I copy+pasted them and made it working..
Something nasty so it worked at the end.

**Comment by thopiekar** [comment]
Haha, found it.. https://github.com/thopiekar/cura-binary-data/commit/43877e4ea45f113948f27ebe3fb2819c07ab6621

And I'm quite sure I just copy+pasted the installers and just did what I often do: 😂🤞

**Comment by LipuFei** [comment]
@thopiekar It shouldn't be necessary to copy the files. The original driver from arduino should just work out of the box.

**Comment by thopiekar** [comment]
I copied these files into the FTDI directory..

This way I was able to install these drivers the same way as the Arduino drivers.
Look close at the commit in my message above :wink:

**Comment by LipuFei** [comment]
@thopiekar If I copy-paste `dpinst-amd64.exe` and `dpinst-i386.exe` into the `arduino\FTDI USB Drivers` folder, then I get the result as below when I try to install with `dpinst-amd64.exe`:
ftdi

If I copy-paste them into `arduino\FTDI USB Drivers\amd64` and `arduino\FTDI USB Drivers\i386` separately, and then run `dpinst-amd64.exe`, I get this:
ftdi-arch

So copy-pasting doesn't work in any of the cases above.

**Comment by thopiekar** [comment]
Strange.. However, let's continue with what we have 😉

**Comment by LipuFei** [comment]
@thopiekar I made a fix and tested. It works. I will close this one.

**Comment by thopiekar** [comment]
@LipuFei Great work, btw.! 👍

**Pull request closed without merging**
