### PR TITLE
Dont install arduino drivers when silent install

### PR DESCRIPTION
**Pull request by jmerriweather**
This should fixes issue https://github.com/Ultimaker/Cura/issues/1245 

Thank you to @basictheprogram for pointing out that https://github.com/Ultimaker/Cura/blob/master/installer.nsi is not actually used and for suggesting the fix

I didn't see @basictheprogram make a PR so I've made this one, if he has made a PR and I've missed it please merge his and close this

### CODE REVIEW

**Comment by ZaxLofful** [comment]
Can we push this through? I need this badly for my SCCM deployment!

**Comment by Appesteijn** [comment]
Giving it a higher prio.

**Comment by LipuFei** [comment]
Hi @jmerriweather , on second thought... I think you can instead have just one `IfSilent` check and skip the complete block of arduino installation.

**Comment by LipuFei** [comment]
Hi @jmerriweather I fixed a small problem and added another skip for VS C++ redistributable in silent installation.

**Pull request merged**
