### PR TITLE
Copy libstd* by regex

### PR DESCRIPTION
**Pull request by thopiekar**
In my case (Ubuntu Xenial) there is no libstdc++.so.6.0.20, but libstdc++.so.6.0.21 installed on the system.
This commit replaces the hardcoded copy instruction with one that uses a regex to locate all libstd\* libraries installed on the system (symlinks included).

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Not sure if this is a good idea. This might cause some hard-to-debug linking errors. Perhaps it is better to at least require some version in 6.0.*? I think we can assume that we haven't targeted anything specific to 6.0.20+ and that 6.0.19 is just as well, right? Once 6.1 or something is needed we can adapt the version number in the build script.

**Comment by thopiekar** [comment]
We don't build libstd on our own. The linkage happens during build and this copy is done after building.
So the libstd libraries which where used during build will be copied and if I'm not wrong there is always one version of libstd which can be installed on a system.
But I can change it to ```/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.*``` if you like

**Comment by awhiemstra** [comment]
Actually, just copying libstdc++.so.6 should suffice since that is symlinked to the actual libstdc++ used. I cannot recall why I specified the version in the first place. I would rather avoid copying all libstdc++ since that would include other versions of libstdc++, including libstdc++ 5 if installed.

Additionally, the current line breaks on any non-debian system since debian is the only one doing lib/${arch} stuff.

**Comment by thopiekar** [comment]
Can someone test it? Maybe we can use a list of paths with regex's...

**Comment by thopiekar** [comment]
Hope this is what you expected :wink:

**Comment by thopiekar** [comment]
@awhiemstra Can you take a look on this again? This PR is required to build packages here in a Ubuntu Wily chroot.

**Pull request closed without merging**
