### PR TITLE
Qt5: Don't build bundled SQLite driver

### PR DESCRIPTION
**Pull request by thopiekar**
By default qmake tries to provide it's own copy of SQLite to build a database driver. As far as I know we don't use SQLite or any other SQL database now.

This will add the needed option to build no SQL driver at all.

### CODE REVIEW

**Comment by awhiemstra** [comment]
In fact, we can skip the entire QtSql module, if it is not already being skipped.

**Comment by thopiekar** [comment]
For me it automatically takes SQLite, even if it is not found on the
system. In this case it takes it's own copy. Adding this will force qmake
to build no SQL driver at all.

**Comment by awhiemstra** [comment]
I meant, we should probably add -skip QtSql in addition to the no sqlite option.

**Comment by thopiekar** [comment]
Ah, ok. Just a moment. I'll add it to this PR.

**Comment by thopiekar** [comment]
But if there is no SQL driver will QtSql be built? Or the other way around: Will qmake look for SQL drivers of QtSql is disabled? Maybe -skip QtSql will be enough.

**Comment by thopiekar** [comment]
QtSql is a part of QtBase. I found no way to disable it, e.g. ```-skip qtsql``` or ```qtbase.qtsql``` didn't work. But I added some more ```-no-sql-*``` to ignore all other database types just in case qmake finds one of them installed on the system.

**Comment by awhiemstra** [comment]
Right, that's probably why it is was not specified in the first place. Hooray for modularity and such :S I guess disabling all SQL drivers is the next best thing. :)

**Pull request merged**
