### PR TITLE
cx_freeze: Adding include_msvcr

### PR DESCRIPTION
**Pull request by thopiekar**
Removes maybe the dependency of installing the msvcr libraries during installation?
Just found this one during some investigations:
https://stackoverflow.com/questions/24103105/how-to-link-msvcr100-dll-to-cx-freeze-program

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Maybe you should try removing the MSVC installation from the Windows installer as well then, and try if it works on a computer that didn't have Cura's MSVC libraries installed yet?

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-4731.

**Comment by alekseisasin** [comment]
@thopiekar, can you remove this msvcr100.dll on your windows (only for testing purposes). 
I think we can make build from this branch and run on different windows. I can try on Windows 7.

**Comment by alekseisasin** [comment]
I tested on my virtual machine and after installation did not discover any new msvcr100.dll files.

**Comment by LipuFei** [comment]
The CRT got packed is `msvcrt.dll`. Perhaps there is no dependency on `msvcrt100.dll` after all?

**Comment by LipuFei** [comment]
With and without this PR, it's still missing VCR140.
image

**Comment by thopiekar** [comment]
@LipuFei Haven't tested this on my own so far, but found this:

**Comment by alekseisasin** [comment]
@thopiekar I tried to remove the msvcrt.dll and expected that Cura will self upload this file to the system, but does not happen. Do you think we still need still this feature?

**Comment by thopiekar** [comment]
No, at least not at the moment. In my point of view, when looking at what @LipuFei found out, I guess either cxFreeze is including the wrong DLL or it is doing it wrong.

So for now, feel free to close the PR, but keep the branch there until I made a backup.

Thank you for asking @alekseiasin ☺️

**Pull request closed without merging**
