### PR TITLE
CMake: Remove some dependencies

### PR DESCRIPTION
**Pull request by thopiekar**
1. If we force to install Python 3.4, we won't get this DEB working on Ubuntu Xenial.
   Python 3.5 is provided here and Python 3.4 has been kicked out of the repositories.
2. Python-OpenGL module is not needed anymore, as we use a alternative workaround -> See Cura.

### CODE REVIEW

**Comment by awhiemstra** [comment]
> If we force to install Python 3.4, we won't get this DEB working on Ubuntu Xenial. Python 3.5 is provided here and Python 3.4 has been kicked out of the repositories.

Well that sucks. This effectively means we will need to publish two packages, one for everything <16.04 and one for 16.04+, since python modules are built for a specific minor version and not back- or forwards compatible as far as I know. Just removing the dependency will just mean you install a broken package since Python will not be able to load the 3.4 extension and then you'd just get an error.

**Comment by thopiekar** [comment]
Well, this is probably what I got here. I tested my DEB in a VM and Scipy is telling me that there is something wrong.
Is there no version of Scipy for example that is compatible with Py 3.4 and Py 3.5? I mean we will still needed to build seperate packages for each Py version, but it will be helpful to use compatible dependencies for both cases.

**Comment by thopiekar** [comment]
Or alternatively: Setup an team account on launchpad and we can build packages in a PPA :wink: 
I will just need to move package builds to the new PPA's.
Or: Lets put our own copy of Python into the DEB :disappointed:

**Comment by thopiekar** [comment]
Oops, the last commit got into the wrong PR..

**Comment by thopiekar** [comment]
```
thopiekar@vm:~$ cura
Traceback (most recent call last):
  File "/opt/cura/bin/cura", line 19, in <module>
    import cura.CuraApplication
  File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 29, in <module>
    from . import PlatformPhysics
  File "/opt/cura/lib/python3/dist-packages/cura/PlatformPhysics.py", line 17, in <module>
    from . import ConvexHullJob
  File "/opt/cura/lib/python3/dist-packages/cura/ConvexHullJob.py", line 6, in <module>
    from UM.Math.Polygon import Polygon
  File "/opt/cura/lib/python3/dist-packages/UM/Math/Polygon.py", line 12, in <module>
    import scipy.spatial
  File "/opt/cura/lib/python3/dist-packages/scipy/spatial/__init__.py", line 91, in <module>
    from .ckdtree import *
  File "__init__.pxd", line 155, in init ckdtree (scipy/spatial/ckdtree/ckdtree.cxx:22466)
ValueError: numpy.dtype has the wrong size, try recompiling
```

**Comment by thopiekar** [comment]
Tried to get Python 3.4.3 built into our DEB, but I still get errors, when building Arcus.
Maybe there is something useful for you to finish that. (In case you want to ship Python in the DEB.)

```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -67,8 +67,6 @@ if(BUILD_OS_WINDOWS)
         # but fails on Win64. So we need an externally built SIP and Arcus bindings on Win64.                                                                                                                                                                         
         set(BUILD_SIP OFF)                                                                                                                                                                                                                                            
     endif()                                                                                                                                                                                                                                                           
-elseif(BUILD_OS_LINUX)                                                                                                                                                                                                                                                
-    set(BUILD_PYTHON OFF)                                                                                                                                                                                                                                             
 endif()                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                       
 set(TAG_OR_BRANCH "master" CACHE STRING "The name of the tag or branch to build")                                                                                                                                                                                     
@@ -125,12 +123,20 @@ if(BUILD_PYTHON)                                                                                                                                                                                                                                 
         BUILD_IN_SOURCE 1                                                                                                                                                                                                                                             
     )                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                       
-    set(PYTHON_EXECUTABLE ${EXTERNALPROJECT_INSTALL_PREFIX}/bin/python3)                                                                                                                                                                                              
-    set(PYTHON_VERSION_MAJOR 3)                                                                                                                                                                                                                                       
-    set(PYTHON_VERSION_MINOR 4)                                                                                                                                                                                                                                       
-else()                                                                                                                                                                                                                                                                
-    find_package(PythonInterp 3.4.0 REQUIRED)                                                                                                                                                                                                                         
-    add_custom_target(Python)                                                                                                                                                                                                                                         
+    SET(ENV{LD_LIBRARY_PATH} "${EXTERNALPROJECT_INSTALL_PREFIX}/lib:$ENV{LD_LIBRARY_PATH}")                                                                                                                                                                           
+    set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "${EXTERNALPROJECT_INSTALL_PREFIX}/lib")                                                                                                                                                                             
+    set(ENV{PATH} "${EXTERNALPROJECT_INSTALL_PREFIX}/bin:$ENV{PATH}")                                                                                                                                                                                                 
+    set(PYTHON_EXECUTABLE "${EXTERNALPROJECT_INSTALL_PREFIX}/bin/python3.4" CACHE FILEPATH "" FORCE)
+    #set(PYTHON_LIBRARY "${EXTERNALPROJECT_INSTALL_PREFIX}/lib/libpython3.4.so" CACHE FILEPATH "" FORCE)
+    #set(PYTHON_INCLUDE_DIR "${EXTERNALPROJECT_INSTALL_PREFIX}/include/python3.4" CACHE FILEPATH "" FORCE)
+    #set(PYTHONINTERP_FOUND TRUE CACHE BOOL "" FORCE)
+    #set(PYTHON_VERSION_MAJOR 3 CACHE STRING "" FORCE)
+    #set(PYTHON_VERSION_MINOR 4 CACHE STRING "" FORCE)
+    #set(PYTHON_VERSION_PATCH 3 CACHE STRING "" FORCE)
+    #set(PYTHON_VERSION_STRING "${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}.${PYTHON_VERSION_PATCH}")
+    
+    find_package(PythonInterp 3.4 REQUIRED)
+    find_package(PythonLibs 3.4 REQUIRED)
 endif()
 
 if(BUILD_QT)
@@ -402,8 +408,8 @@ ExternalProject_Add(Uranium
 
 ExternalProject_Add(Cura
     DEPENDS Uranium CuraEngine
-    GIT_REPOSITORY https://github.com/ultimaker/Cura
-    GIT_TAG origin/${TAG_OR_BRANCH}
+    GIT_REPOSITORY https://github.com/thopiekar/Cura
+    GIT_TAG origin/master-generate-cura-desktop
     CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNALPROJECT_INSTALL_PREFIX} -DURANIUM_SCRIPTS_DIR= -DCURA_VERSION=${CURA_VERSION}
 )
 
@@ -560,8 +566,13 @@ elseif(BUILD_OS_LINUX)
         "${CMAKE_COMMAND} -E make_directory ${package_dir}/usr/share/applications"
         "${CMAKE_COMMAND} -E rename ${CMAKE_BINARY_DIR}/inst/bin/cura ${CMAKE_BINARY_DIR}/inst/bin/cura.real"
         "${CMAKE_COMMAND} -E copy   ${CMAKE_SOURCE_DIR}/cura          ${package_dir}/usr/bin"
-        "${CMAKE_COMMAND} -E copy /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20 ${package_dir}/opt/cura/lib/libstdc++.so.6"
     )
+
+    set(CPACK_INSTALL_COMMANDS ${CPACK_INSTALL_COMMANDS} "mkdir -pv ${package_dir}/opt/cura/lib/")
+    file(GLOB libstdc_libraries "/usr/lib/x86_64-linux-gnu/libstdc++.so.*")
+    foreach(libstdc_library ${libstdc_libraries})
+        set(CPACK_INSTALL_COMMANDS ${CPACK_INSTALL_COMMANDS} "cp -rfv ${libstdc_library} ${package_dir}/opt/cura/lib/")
+    endforeach()
 endif()
 
 set(CPACK_PACKAGE_NAME "Cura")
thopiekar@hp:/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build/build$ make Arcus
-- Building Cura master.0.0-master
-- Configuring done
-- Generating done
-- Build files have been written to: /media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build/build
[ 24%] Built target Python
[ 52%] Built target Protobuf
[ 76%] Built target Sip
[ 76%] Performing update step for 'Arcus'
Aktueller Branch HEAD ist auf dem neuesten Stand.
[ 80%] Performing configure step for 'Arcus'
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3.4.0" (found
  [....]/Projekte/GIT/Ultimaker/cura-build/build/inst/bin/python3.4)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindPythonInterp.cmake:163 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindSIP.cmake:27 (find_package)
  CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
See also "[....]/Projekte/GIT/Ultimaker/cura-build/build/Arcus-prefix/src/Arcus-build/CMakeFiles/CMakeOutput.log".
See also "[....]/Projekte/GIT/Ultimaker/cura-build/build/Arcus-prefix/src/Arcus-build/CMakeFiles/CMakeError.log".
CMakeFiles/Arcus.dir/build.make:108: die Regel für Ziel „Arcus-prefix/src/Arcus-stamp/Arcus-configure“ scheiterte
make[3]: *** [Arcus-prefix/src/Arcus-stamp/Arcus-configure] Fehler 1
CMakeFiles/Makefile2:443: die Regel für Ziel „CMakeFiles/Arcus.dir/all“ scheiterte
make[2]: *** [CMakeFiles/Arcus.dir/all] Fehler 2
CMakeFiles/Makefile2:455: die Regel für Ziel „CMakeFiles/Arcus.dir/rule“ scheiterte
make[1]: *** [CMakeFiles/Arcus.dir/rule] Fehler 2
Makefile:270: die Regel für Ziel „Arcus“ scheiterte
make: *** [Arcus] Fehler 2
```

**Comment by awhiemstra** [comment]
We actually have some plans to move to Python 3.5 so we can add type annotations. Additionally, I want to start using cx_freeze instead of py2exe and py2app since cx_freeze can also be used on Linux, which would greatly reduce the amount of stuff we need to include in the package.

**Pull request closed without merging**
