### PR TITLE
README: Remove instruction to install PyQt5

### PR DESCRIPTION
**Pull request by thopiekar**
We are installing it in cura-build-environment!

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Yes we are, but it's still a dependency. Most of the dependencies built in cura-build-environment are listed there.

**Comment by thopiekar** [comment]
.. and cura-build-environment provides it. So we actually don't depend here on PyQt5, but on cura-build-environment, which comes with PyQt5.
This is how I interpret it.

**Comment by Ghostkeeper** [comment]
Well yes, but so is Numpy, Scipy, Numpy-STL, Python, etc, but those are still listed.

I think it's better to say that "We need these dependencies. You can install them yourself or use cura-build-environment to build them automatically." or something of the sort.

**Comment by thopiekar** [comment]
But still.. then the question is like: Do we really need them for cura-build?
Eg. if I had Python 3.5, Numpy and all the others installed on my host environment, then would cura-build take them from there or still expect something like a prefix, like we create with cura-build-environment?

**Comment by Ghostkeeper** [comment]
Cura-build should take them from there if you install them manually, yes.

**Pull request closed without merging**
