### PR TITLE
Change to using bash scripts. 

### PR DESCRIPTION
**Pull request by derekhe**
Tested on refresh installed ubuntu 15.04 and it is working.

### CODE REVIEW

**Comment by awhiemstra** [comment]
While I have no real objections to the change and thus merged it, I have also just pushed the changes I made to support building debian packages using this. Can you see if that covers your use case?

**Comment by derekhe** [comment]
I will try cmake later.

My original idea was that when a user install a new ubuntu 15.04, he/she can just use this script to get everything ready, including prepare for the git, source code and all the dependencies. 

I felt it was really hard to figure out how cura, cura-engine and other dependencies were built when I first try to build and run the 15.06. Even the build is fine, the resource path problem will stop then from seeing the correct UI.

So I hope this script can help other developers to quick start to build and run the project without other knowledge. CMake will still cause some trouble when using python3 sometimes.

**Comment by awhiemstra** [comment]
Fair enough. I will leave the Ubuntu script alone for now, though eventually we should probably move it to the Cura repository, since this is really intended as a repository for packaging scripts.

**Comment by derekhe** [comment]
ok, np :)

**Pull request merged**
