### PR TITLE
CURA-6187 Fix docker

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
There is a merge conflict in how PythonInterp is found right now.

**Comment by LipuFei** [comment]
@Ghostkeeper Fixed. I think those check can be moved to Uranium because Uranium needs to know its dependencies. Not `cura-build`.

**Comment by Ghostkeeper** [comment]
It's currently giving me the following error:
```
[100%] Packaging Projects...
Cleaning old package directory...
Running cx_Freeze to generate executable...
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 144, in <module>
    executables = executables
  File "/srv/cura-build-environment/lib/python3.5/site-packages/cx_Freeze/dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "/srv/cura-build-environment/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/srv/cura-build-environment/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/srv/cura-build-environment/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/srv/cura-build-environment/lib/python3.5/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/srv/cura-build-environment/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/srv/cura-build-environment/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/srv/cura-build-environment/lib/python3.5/site-packages/cx_Freeze/dist.py", line 218, in run
    zipExcludePackages = self.zip_exclude_packages)
  File "/srv/cura-build-environment/lib/python3.5/site-packages/cx_Freeze/freezer.py", line 149, in __init__
    self._VerifyConfiguration()
  File "/srv/cura-build-environment/lib/python3.5/site-packages/cx_Freeze/freezer.py", line 468, in _VerifyConfiguration
    sourceFileName)
cx_Freeze.freezer.ConfigError: cannot find file/directory named /srv/cura-build-environment/openssl.cnf
```
Is that something I'm doing wrong?

**Comment by LipuFei** [comment]
This PR needs https://github.com/Ultimaker/cura-build-environment/pull/62

**Pull request merged**
