### PR TITLE
Windows installer got ultimaker icons and banner

### PR DESCRIPTION
**Pull request by ckielstra**
- Added an Ultimaker bitmap to the installer. Supplied by Menno.
- Added Ultimaker icons to the installer and un-installer.
- Replaced the smaller icons in the file by neater versions (better scaled and no color dithering on the solid color planes).
- Save 330 kb on the icon file by using compression for the 256x256 image (only this image to maintain backwards compatibility)

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-5700

**Comment by alekseisasin** [comment]
Can we use a logo from S5 printer?

ultimaker s5_1

**Comment by thopiekar** [comment]
Well, wouldn't do this because the icon will only survive until the next product is out.
After that someone will need to update it again.

Additionally this icon would make people think that this Cura Version might be for S5-only.

**Comment by alekseisasin** [comment]
@thopiekar , I agree, but it is newer, I was thinking it is better than UM3, then why not use the latest printer model.

**Pull request merged**
