### PR TITLE
Set LD_LIBRARY_PATH for cx_Freeze so it finds the right libraries

### PR DESCRIPTION
**Pull request by smartavionics**
We need cx_Freeze to find our Qt libraries not the system libraries.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Hmm, I suppose this was working all right for us because we install the build environment to our system on the build server...

**Comment by smartavionics** [comment]
Yes, because when cura qt moved to 5.10 and my old Ubuntu system libraries are still 5.5? the AppImage failed.

**Comment by Ghostkeeper** [comment]
Qt is not currently in Ubuntu's [manifest](http://releases.ubuntu.com/19.04/ubuntu-19.04-desktop-amd64.manifest) but maybe it was in the past.

**Comment by smartavionics** [comment]
Don't know he relevance of that but, anyway, you still want the cx_Freeze to pick up the libraries installed by cura-build-environment rather than the system libraries, don't you?

**Comment by Ghostkeeper** [comment]
Yes, I'd think that this change is relevant for safety and stability of the build in the future.

**Comment by smartavionics** [comment]
Sorry, I didn't intend to close the issue, finger trouble!

**Comment by Ghostkeeper** [comment]
:smile: Github seems to be having some trouble today. Messages have been popping up saying "You can't comment at this time."

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-6623.

**Comment by LipuFei** [comment]
Hi @smartavionics , sorry for the late response. I checked that on our build server, we do set `LD_LIBRARY_PATH` before we call `cmake` and `make`, that's probably why we "don't need" this line, but I am not sure. I will test your change now.

Just for my curiosity, could you check your PyQt5 dynamic libraries see which Qt `.so` files they are linked to? For example, below is the results from our build server:

```
[...@cura-linux-build PyQt5]$ pwd
/.../env/master/inst/lib/python3.5/site-packages/PyQt5

[ultimaker@cura-centos-build PyQt5]$ ls
Qt.so       QtGui.pyi          QtNetworkAuth.so    QtQml.pyi           QtQuickWidgets.so  QtTest.pyi        QtWidgets.so     _QOpenGLFunctions_2_0.so       pylupdate.so
QtCore.pyi  QtGui.so           QtOpenGL.pyi        QtQml.so            QtSql.pyi          QtTest.so         QtX11Extras.pyi  _QOpenGLFunctions_2_1.so       pylupdate_main.py
QtCore.so   QtNetwork.pyi      QtOpenGL.so         QtQuick.pyi         QtSql.so           QtWebSockets.pyi  QtX11Extras.so   _QOpenGLFunctions_4_1_Core.so  pyrcc.so
QtDBus.pyi  QtNetwork.so       QtPrintSupport.pyi  QtQuick.so          QtSvg.pyi          QtWebSockets.so   QtXml.pyi        __init__.py                    pyrcc_main.py
QtDBus.so   QtNetworkAuth.pyi  QtPrintSupport.so   QtQuickWidgets.pyi  QtSvg.so           QtWidgets.pyi     QtXml.so         __pycache__                    uic

[...@cura-linux-build PyQt5]$ ldd QtCore.so
	linux-vdso.so.1 =>  (0x00007ffe87ffe000)
	libQt5Core.so.5 => /.../env/master-20191025_win_docker/inst/lib/libQt5Core.so.5 (0x00007fda9088f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fda90667000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fda90361000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fda900dd000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fda8fec6000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fda8fb32000)
	libz.so.1 => /.../env/master-20191025_win_docker/inst/lib/libz.so.1 (0x00007fda8f916000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fda8f711000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007fda8f50d000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fda8f1f6000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fda8efed000)
	/lib64/ld-linux-x86-64.so.2 (0x000056201eac1000)
[...@cura-linux-build PyQt5]$
```

**Comment by smartavionics** [comment]
Hi @LipuFei , I install cura into /opt/cura.
````
/opt/cura/lib/python3.5/site-packages/PyQt5$ ldd QtCore.so 
	linux-vdso.so.1 =>  (0x00007ffcd7dc7000)
	libQt5Core.so.5 => /opt/cura/lib/libQt5Core.so.5 (0x00007f4902dc1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4902a3f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4902675000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4902458000)
	libz.so.1 => /opt/cura/lib/libz.so.1 (0x00007f490223c000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f490202b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4901e27000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f4901b16000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f490180d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f49015f6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f49038fa000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f4901386000)
````

**Comment by LipuFei** [comment]
Well, that looks similar. I guess `LD_LIBRARY_PATH` is necessary.

**Pull request merged**
